<!DOCTYPE html>
<html>
  <head>
  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="{$page_description}">
    <meta name="viewport" content="width=device-width">
    
    <title><?php echo $page_title ?></title>
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo_global_url('css/sticky.css'); ?>" type="text/css">
    
<?php
    if (isset($stylesheets)) {
        foreach ($stylesheets as $stylesheet) {
            echo "<link rel='stylesheet' href='{$stylesheet}' type='text/css'>";
        }
    }
?>
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js" type='text/javascript'></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js" type='text/javascript'></script>

<?php
    if (isset($scripts)) {
        foreach ($scripts as $script) {
            echo "<script src='{$script}' type='text/javascript'></script>";
        }
    }
?>
    
  </head>
  <body>
    
    <div class="modal fade bs-example-modal-lg" id="termsOfUse" tabindex="-1" role="dialog" aria-labelledby="termsOfUseLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title" id="termsOfUseLabel">Terms of Use</h3>
                </div>
                <div class="modal-body">
                    <h5>Terms of Use for this Site</h5>

                    <p>
                        All visitors agree to declare the webmaster, Bryan Stockus, the Benevolent Dictator for Life over this site.
                    </p>
                    
                </div>
            </div>
        </div>
    </div>
    
    <div class="modal fade bs-example-modal-lg" id="privacyModal" tabindex="-1" role="dialog" aria-labelledby="privacyModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title" id="privacyModalLabel">Privacy Policy</h3>
                </div>
                <div class="modal-body">
                    <h5>Our Policy for Protecting Your Online Privacy</h5>

                    <p>
                        This website uses Google Analytics to help Analyse how users use the site. The tool uses "cookies," 
                        which are text files placed on your computer, to collect standard Internet log information and visitor 
                        behavior information in an anonymous form. The information generated by the cookie about your use of the 
                        website (including IP address) is transmitted to Google. This information is then used to evaluate visitors' 
                        us of the webiste and to compile statistical reports on website activity for BryanStockus.net.
                    </p>
                    
                    <p>
                        We will never (and will not allow any third party to) use the statistical analytics tool to track or to collect 
                        any Personally Identifiable Information (PII) of visitors to our site. Google will not associate your IP address 
                        with any other data held by Google. Neither we nor Google will link, or seek to link, an IP address with the 
                        identity of a computer user. We will not associate any data gathered from this site with any Personally 
                        Identifiable Information from any source, unless you explicitly submit that information via a fill-in form 
                        on our website.
                    </p>
                    
                    <p>
                        You may choose to accept or decline cookies. Most Web browsers automatically default to accept them, but you can 
                        usually modify your browser setting to decline cookies. If you reject cookies by changing your browser settings 
                        then be aware that this may disable some of the functionality on our Website.
                    </p>

                    <p>
                        User’s Personal Information: Visitors to our website may be able to register to use our services, attend events, 
                        make a purchase, join a community or upload/download information. When you register, you will provide personal 
                        information such as name, address, email, telephone number or facsimile number and other relevant information. If 
                        you are making a purchase, we will request financial information including your credit card number, expiration 
                        date, and security code. Any financial information we collect is used only to bill you for your purchase. This 
                        information may be forwarded to your credit card provider. We will not disclose personally identifiable 
                        information we collect  you to third parties without your permission except to the extent necessary, including: 
                        To fulfill your requests, to protect ourselves from liability, to comply with the terms and conditions of 
                        our internet host provider.
                    </p>
                    
                    <p><strong>3rd Party Policies</strong></p>
                    
                    <p>
                        Related services and offerings linked to or from this website have their own privacy statements that can be viewed 
                        by clicking on the corresponding links within each respective website. Since we do not have control over the 
                        policies or practices of participating merchants and other third parties, we are not responsible for the privacy 
                        practices or contents of those sites. We recommend you review their policies before you provide any personal 
                        information or complete any transaction with them.
                    </p>
                    
                </div>
            </div>
        </div>
    </div>
    
    <?php echo isset($modal) ? $modal : ""; ?>
    
    <?php echo $navbar; ?>
    
    <div class='container'>
        <?php echo $content; ?>
    </div>
    
    <footer class="footer">
    	<div class="container">
    	    <span class='pull-right'>
    	        
    	        Check my Code out: 
    	        <a href="https://bitbucket.org/bstockus/"><i class="fa fa-bitbucket"></i></a> 
    	        <a href="https://github.com/bstockus/"><i class="fa fa-github"></i></a> 
    	        | Long live <i class="fa fa-apple"></i> &amp; <i class="fa fa-linux"></i>!
    	    
<?php
                if (is_development_mode()) {
?>
                    <span class="label label-danger">DEVELOPMENT</span>
<?php
                }
?>
            
            </span>
            
    		&copy; 2015 Bryan Stockus, All Rights Reserved.    |    
    		<a href="#" data-toggle="modal" data-target="#privacyModal">Privacy Policy</a> | 
    		<a href="#" data-toggle="modal" data-target="#termsOfUse">Terms of Use</a> | 
    		<a href="<?php echo_global_url('contact'); ?>">Contact</a> |
    		<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
    		    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png">
    		</a>
    	</div>
    </footer>
  </body>
</html>